language: "en_core_web_md"

pipeline: "pretrained_embeddings_spacy"

policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 3
  - name: MemoizationPolicy
    max_history: 3
  - name: FormPolicy